### ISSUE TITLE
Add references to existing libraries for working with OMM, TLES, and SGP4/SDP4

### ISSUE THREAD

**Issue by wardev** [DigitalArsenal/spacedatastandards.org#5]
Hi,

Do you plan to include a list of existing libraries that parse/write OMMs and propagate TLES? In many cases that would be easier for developers than asking them to maintain their own parser, writer, and propagator.

For Java Orekit can parse/write OMM, TLES and has a SGP4/SDP4 propagator: https://orekit.org.

Best Regards,
Evan

**Comment by TJKoury** [comment]
@wardev Yes, we absolutely can do that!  I'll start a Wiki.

**Comment by TJKoury** [comment]
[Wiki](https://github.com/DigitalArsenal/spacedatastandards.org/wiki/Software).
